watch_stylesheet: false
watch_config: false
debug: false
update_check: false
glazewm:
  start_command: glazewm.exe start
  stop_command: glazewm.exe command wm-exit
  reload_command: glazewm.exe command wm-exit && glazewm.exe start
bars:
  primary-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      align: "center"
    animation:
      enabled: true
      duration: 900
    blur_effect:
      enabled: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true # This interferes with apps in full-screen. Notably while watching videos in full screen
      hide_on_fullscreen: false
      hide_on_maximized: false
      auto_hide: false
    layouts:
      left:
        alignment: "left"
        stretch: true
      center:
        alignment: "center"
        stretch: true
      right:
        alignment: "right"
        stretch: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["glazewm_binding_mode", "glazewm_workspaces", "active_window"]
      center: ["clock", "lines", "battery"]
      right: ["system-tray", "wifi", "volume", "media", "notifications", "notes", "open_meteo", "sysinfo", "power_menu"]
widgets:
  open_meteo:
    type: "yasb.open_meteo.OpenMeteoWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: " {temp} / \u2601 {min_temp} / \u2600 {max_temp} / \u2602 {humidity}"
      update_interval: 600
      hide_decimal: true
      units: "metric"
      tooltip: false
      icons:
        sunnyDay: "\uE30D"
        clearNight: "\uE32B"
        cloudyDay: "\uE312"
        cloudyNight: "\uE311"
        drizzleDay: "\uDB81\uDE7E"
        drizzleNight: "\uDB81\uDE7E"
        rainyDay: "\uE308"
        rainyNight: "\uE333"
        snowyDay: "\uE30A"
        snowyNight: "\uE335"
        foggyDay: "\uE303"
        foggyNight: "\uE346"
        thunderstormDay: "\uE30F"
        thunderstormNight: "\uE338"
        default: "\uEBAA"
      callbacks:
        on_right: "toggle_card"
        on_middle: "do_nothing"
        on_left: "toggle_label"
      weather_card:
        blur: false
        round_corners: false
        round_corners_type: "normal"
        border_color: "none"
        alignment: "center"
        direction: "down"
        icon_size: 48
        show_hourly_forecast: true
        time_format: "24h"
        hourly_point_spacing: 76
        hourly_icon_size: 24
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "#8EAEE8"
        current_line_width: 1
        current_line_style: "dot"
        hourly_gradient:
          enabled: false
          top_color: "#8EAEE8"
          bottom_color: "#2A3E68"
        hourly_forecast_buttons:
          enabled: true
          default_view: "temperature"
          temperature_icon: "\uDB81\uDD99"
          rain_icon: "\uDB81\uDD96"
          snow_icon: "\uDB81\uDD98"
        weather_animation:
          enabled: false
          snow_overrides_rain: true
          temp_line_animation_style: both
          rain_effect_intensity: 1.0
          snow_effect_intensity: 1.0
          scale_with_chance: true
  notes:
    type: "yasb.notes.NotesWidget"
    options:
      label: "<span>\uDB83\uDEBF</span>"
      menu:
        blur: false
        round_corners: false
        border_color: "None"
        alignment: "right"
        direction: "down"
        offset_top: 4
        offset_left: 44
        max_title_size: 150
        show_date_time: true
      icons:
        note: "\uDB82\uDD0C"
        delete: "\uDB82\uDDE7"
        copy: "\uF4BB"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_menu"
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uDB80\uDD78</span>"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_notification"
  sysinfo:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "sysinfo"
      widgets: ["disk", "memory", "cpu"]
      collapse_options:
        enabled: true
        expanded_label: "\uDB80\uDEFC"
        collapsed_label: "\uDB80\uDEFD"
        label_position: "right"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uDB80\uDECA</span> {space[used][percent]}"
      label_alt: "<span>\uDB80\uDECA</span> {space[used][gb]}/{space[total][gb]}"
      volume_label: "C"
      update_interval: 60
      group_label:
        volume_labels: ["C", "D", "E", "F"]
        show_label_name: true
        blur: false
        round_corners: false
        round_corners_type: "small"
        border_color: "None"
        alignment: "right"
        direction: "down"
        offset_top: 4
        offset_left: 40
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec explorer"
        on_right: "toggle_group"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uEFC5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uEFC5</span> {virtual_mem_free}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 20
        medium: 60
        high: 90
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uF4BC</span> {info[percent][total]:.0f}%"
      label_alt: "<span>\uF4BC</span> {info[freq][current]} GHz"
      update_interval: 1000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      callbacks:
        on_right: "exec cmd /c Taskmgr"
        on_left: "toggle_label"
  system-tray:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "system-tray"
      widgets: ["systray", "lines"]
      collapse_options:
        enabled: true
        expanded_label: "\uF054"
        collapsed_label: "\uF053"
        label_position: "left"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\uF438"
      label_expanded: "\uF44A"
      label_position: "left" # Can be "left" or "right"
      icon_size: 13 # Can be any integer between 8 and 64
      pin_click_modifier: "ctrl" # Can be "ctrl", "alt" or "shift"
      show_unpinned: true
      show_unpinned_button: false
      show_battery: false
      show_volume: false
      show_network: false
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "Offline"
      hide_if_offline: true
      monitor_exclusive: false
      enable_scroll_switching: false
  glazewm_binding_mode:
    type: "glazewm.binding_mode.GlazewmBindingModeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {binding_mode}"
      hide_if_no_active: true
      icons:
        resize: "\uDB82\uDE68"
        pause: "\uF28C"
      binding_modes_to_cycle_through: ["none", "resize", "pause"]
      callbacks:
        on_left: "next_binding_mode"
        on_right: "disable_binding_mode"
  media:
    type: "yasb.media.MediaWidget"
    options:
      class_name: "media-text"
      label: "<span>\u266A</span>"
      hide_empty: false
      callbacks:
        on_left: "toggle_media_menu"
        on_right: "toggle_media_menu"
      show_thumbnail: false
      controls_only: false
      controls_left: false
      controls_hide: true
      media_menu:
        blur: false
        round_corners: false
        border_color: "None"
        alignment: "left"
        direction: "down"
        offset_top: 4
        offset_left: -18
        thumbnail_corner_radius: 0
        thumbnail_size: 140
        max_title_size: 80
        max_artist_size: 20
        show_source: false
        show_volume_slider: true
      media_menu_icons:
        play: "\uDB83\uDF1B"
        pause: "\uDB80\uDFE4"
        prev_track: "\uDB83\uDF28"
        next_track: "\uDB83\uDF27"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M}"
      label_alt: "{%A, %B %d %Y / %H:%M}"
      tooltip: false
      calendar:
        blur: false
        round_corners: false
        alignment: "center"
        direction: "down"
        border_color: None
        show_holidays: true
        holiday_color: "#FF6E00"
        country_code: "IN"
        extended: false
      callbacks:
        on_right: "toggle_calendar"
        on_left: "toggle_label"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>\uF1EB</span>"
      label_alt: "{wifi_name}"
      update_interval: 1000
      callbacks:
        on_right: "exec explorer.exe ms-availablenetworks:"
        on_left: "toggle_label"
      ethernet_label: "<span>\uF1EB</span>"
      ethernet_label_alt: "{ip_addr}"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span class='vol-level'>{level}</span>"
      tooltip: false
      icons:
        - "\uE74F" # Icon for muted
        - "\uE994" # Icon for 0-10% volume
        - "\uE994" # Icon for 11-30% volume
        - "\uE994" # Icon for 31-60% volume
        - "\uE994" # Icon for 61-100% volume
      callbacks:
        on_right: "exec SndVol.exe"
        on_left: "toggle_label"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{percent}% {power}W"
      label_alt: "<span>{icon}</span>{percent}%"
      update_interval: 5000
      hide_unsupported: true
      time_remaining_natural: false
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: false
      status_thresholds:
        critical: 10
        low: 25
        medium: 50
        high: 75
        full: 100
      status_icons:
        icon_charging: "\uDB85\uDC0C"
        icon_critical: "\uEBA1"
        icon_low: "\uEBA3"
        icon_medium: "\uEBA6"
        icon_high: "\uEBA9"
        icon_full: "\uEBAA"
      callbacks:
        on_left: "toggle_label"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "~"
      uptime: true
      show_user: true
      profile_image_size: 180
      menu_style: "fullscreen"
      blur: false
      blur_background: true
      animation_duration: 120
      button_row: 6
      buttons:
        lock: ["\uF456", "Lock"]
        sleep: ["\uF4EE", "Sleep"]
        signout: ["\uF08B", "Sign out"]
        shutdown: ["\uF011", "Shut Down"]
        restart: ["\uEAD2", "Restart"]
        cancel: ["\uDB81\uDF3A", "Cancel"]
      keybindings:
        - keys: "ctrl+alt+end"
          action: "toggle_power_menu"
      callbacks:
        on_right: "toggle_power_menu"
  active_window: # TO-DO: Add rewrite rules for specific apps
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[app_name]}"
      label_alt: "{win[process]}"
      label_icon: false
      max_length: 75
      monitor_exclusive: false
      callbacks:
        on_left: "do_nothing"
      rewrite:
        # Strip trailing “.exe” (case-insensitive) and lowercase:
        - pattern: "^(.+?)\\.exe$"
          replacement: "\\1"
          case: title

        # Uppercase UI
        - pattern: "\\bui\\b"
          replacement: "UI"

        - pattern: "^ShareX .*"
          replacement: ""

        - pattern: "^ShareX - .*"
          replacement: "ShareX"

        - pattern: "Remove large amounts of unwanted applications quickly"
          replacement: "Bulk Crap Uninstaller"

        - pattern: "WireGuard: Fast, Modern, Secure VPN Tunnel"
          replacement: "WireGuard"

        - pattern: "Wallpaper Engine User Interface"
          replacement: "Wallpaper Engine"

        - pattern: "Adobe Illustrator 2026"
          replacement: "Adobe Illustrator"

        - pattern: "Adobe Photoshop 2026"
          replacement: "Adobe Photoshop"

        - pattern: "Steam Client WebHelper"
          replacement: "Steam"

  lines:
    type: "yasb.custom.CustomWidget"
    options:
      label: "|"
      label_alt: "|"
      class_name: "separator-widget"
      callbacks:
        on_left: "do_nothing"
show_systray: true
